'use client'
import './globals.css'
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })
import { useEffect } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest:'/manifest.json'
}

export default function RootLayout({ children }) {
  
  useEffect(() => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/service-worker.js');
    }
  }, []);
  
  
  return (
    <html lang="en">
       <body className={inter.className}>
      {children}</body>
    </html>
  )
}